server:
  port: 8080

mybatis:
  type-aliases-package: com.atguigu.entity
  mapper-locations: classpath:mybatis/**/*.xml
spring:
  application:
    name: cloud-provider
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/student?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 600

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: cloud-provider  #自定义服务名称
    prefer-ip-address: true      #访问路径显示IP地址

info:
  app.name: SpringCloudProviderProject
  artifactId: ${project.artifactId}
  version: ${project.version}
  companyname: chinaunicom
